% Auto-generated by MATLAB on 2018/03/29 00:12:43

% Modified by MD. Monirul Islam
% sozebislam@gmail.com



filename = 'MM.txt'; %change the file name according to your need
delimiter = '\t';
startRow = 2;

%% Format string for each line of text:
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
%VarName1 = dataArray{:, 1};

%% Reading data from epoch inds.speaking_inds
load('epoch_inds.mat')
[rr cc] = size(thinking_inds);
trial_data= zeros(cc, 64, 5000);
for k = 1 : cc
l_lim = thinking_inds{k}(1);
h_lim = thinking_inds{k}(2);
diff = h_lim - l_lim + 1;
for j = 1  : 64

 trial_data(k, j, 1 : diff) = dataArray{:, j+1}(l_lim : h_lim);

end
end
%% Clear temporary variables
clearvars filename delimiter startRow cc formatSpec fileID dataArray ans clearing_inds diff h_lim j k l_lim rr speaking_inds thinking_inds  ;

save('trial_data.mat')